### ISSUE TITLE
datapacks items

### ISSUE THREAD

**Issue by doublewolf7** [CiscuLog/Survivor-s-Elegy#11]
nothing looks right. is their a texture pack i dident get?

**Comment by CiscuLog** [comment]
Yes.
[https://github.com/CiscuLog/Survivor-s-Elegy/wiki/Frequently-Asked-Questions#where-can-i-find-the-resourcepack](https://github.com/CiscuLog/Survivor-s-Elegy/wiki/Frequently-Asked-Questions#where-can-i-find-the-resourcepack)
