### ISSUE TITLE
Won't Stop Giving Items

### ISSUE THREAD

**Issue by brandonkrabach** [CiscuLog/Survivor-s-Elegy#2]
I first added the datapack to my server and found that I was continuously being given random assortments of the new items that were added. I then tested to see if this was an issue just with my server, but it ended up doing the same thing on a single player world.

I am currently playing on version 1.20.1

I have tried with and without the newest version of fabric 1.20.1 as of the time writing this. The server is a Fabric 1.20.1 server.

I have had this issue once before with some datapack years ago that I gave up on using, because I couldn't figure out a solution. I am hoping this is something that I have missed, but otherwise, this version is unplayable with this issue.

**Comment by CiscuLog** [comment]
This sounds a lot like you're using another datapack or mod that gives you all recipes periodically. Are you?

**Comment by brandonkrabach** [comment]
That is correct! I am using the one from Vanilla Tweaks. I will get rid of that. Thank you very much
