### ISSUE TITLE
Resource pack glitch

### ISSUE THREAD

**Issue by jepo1234** [CiscuLog/Survivor-s-Elegy#5]
When I load the Survivors Elegy resource pack in, even without any other packs, all armour pieces looks broken, as in the armour is stretched out across the entire player character.

**Comment by CiscuLog** [comment]
This error happens when using shaders. Are you using shaders?

**Comment by satoon10** [comment]
Where do I download the resourcepack?

**Comment by satoon10** [comment]
modrinth didnt have the resourcepack, but in curseforge it had

**Comment by CiscuLog** [comment]
Modrinth DOES have the resourcepack, it's just a bit hidden down in "Files" for some reason
[example](https://modrinth.com/datapack/survivors-elegy/version/0.8.5#:~:text=Optimised%20randomisers-,Files,-Datapack_Survivors_Elegy_alpha_v0.8.5.zip(1.13)
