### ISSUE TITLE
Resource pack and placeholder name problem

### ISSUE THREAD

**Issue by DeferentRat6594** [CiscuLog/Survivor-s-Elegy#8]
for some reason none of the textures or names work properly 
![Screenshot 2024-03-03 163119](https://github.com/CiscuLog/Survivor-s-Elegy/assets/153131948/13e7516d-0d1d-486d-9937-1de0ac99be5a)
![Screenshot 2024-03-03 163012](https://github.com/CiscuLog/Survivor-s-Elegy/assets/153131948/cdf909fe-bd04-404f-b23c-ff77b14f5b66)
IDK if i did something wrong but the resource pack is downloaded, and I have the data pack physically in

![Screenshot 2024-03-03 163550](https://github.com/CiscuLog/Survivor-s-Elegy/assets/153131948/67d42930-7eea-4c2c-929c-434e6895b8d9)
![Screenshot 2024-03-03 163501](https://github.com/CiscuLog/Survivor-s-Elegy/assets/153131948/fb47447e-cd7a-4400-aff7-b5864f60a9d7)

**Comment by CiscuLog** [comment]
Is there any relevant information on the game's logs? Can't really tell you what the issue is with what you've given me since I can't reproduce this.

**Comment by CiscuLog** [comment]
It seems the issue is the resourcepack is not being loaded correctly.
Due to the lack of information necessary to resolve the user's issue, this thread will be closed.
