### ISSUE TITLE
A few issues with the survivors elegy data pack for 1.20.4

### ISSUE THREAD

**Issue by Tarzal** [CiscuLog/Survivor-s-Elegy#9]
First of all, tridents no longer work, try right clicking them they, can’t throw them.
Next up the zombification cannot be cured. Golden Apples or enchanted golden apples do not work. May be doing something wrong, but if I remember correctly golden apples cure the phage right?
If I am wrong please tell me how to cure said phage.
Rest everything seems all right, these are the most glaring issues as of now which I hope you rectify for this version.
Otherwise, it is cool data pack, what with all the copper armour, craftable trident, zombification etc.

**Comment by CiscuLog** [comment]
Tridents should work fine.
Zombification can be cured by eating a gapple WHILE WEAKENED, as in having the weakness effect
